sonar.projectKey=backend
sonar.projectName=backend

sonar.sources=.

sonar.exclusions=node_modules/**,blockchain-project/node_modules/**,**/*.java

sonar.host.url=http://host.docker.internal:9001

sonar.login=sqa_53f2b971de641b9a5deda7437feca89d87323cc9
