sonar.projectKey=backend
sonar.projectName=backend

sonar.sources=.

sonar.exclusions=node_modules/**,blockchain-project/node_modules/**,**/*.java

sonar.host.url=http://host.docker.internal:9001
sonar.token=sqa_4df892e1a2aedd70b99d2516067a4018ab9c35e1
