sonar.projectKey=backend
sonar.projectName=backend

sonar.sources=.

sonar.exclusions=node_modules/**,blockchain-project/node_modules/**,**/*.java

sonar.host.url=http://host.docker.internal:9001

sonar.login=sqa_44d4ef107a5ce23090e67189496e16c8ce2a7877
